/// <reference types="cypress" />
const { faker } = require('@faker-js/faker');

describe('Login and Navigation Tests', () => {
     beforeEach(() => {
          cy.visit("https://mbqa.site/")
     cy.get("a[class='ms-btn-lg ms-btn-primary']").click()
     console.log('Opened Sign Up page')
     cy.wait(2000)
     cy.get(".text-link.para-16").click()
     console.log('Opened Login page')
     cy.wait(2000)
     cy.get("input[name='email']").type('himanshupant.qa+rohit@gmail.com')
     cy.wait(2000)
     cy.get("button[type='submit']").click()
     cy.wait(2000)
     cy.get(':nth-child(1) > .cstm-input').clear()
     cy.get(':nth-child(1) > .cstm-input').type('himanshupant.qa+rohit@gmail.com')
     cy.wait(2000)
     cy.get("input[placeholder='Enter Your Password']").type('Rohit@123')
     cy.wait(2000)
     cy.get("button[type='submit']").click()
     cy.wait(2000)
     })
     //  Test case for adding a deal without filling details
    it('Add deal without filling details', () => {
    cy.url().should('include', '/dashboard')
    cy.wait(2000)
    cy.get('.ri-function-line').click()
    cy.wait(2000)
    cy.get(':nth-child(1) > .align-items-start > .d-flex > :nth-child(3) > .py-1').click()
    cy.wait(2000)
    cy.get(':nth-child(1) > .form-field-wrapper > .cstm-input').select('lead');
    cy.wait(2000)
    cy.get('.side-modal-body > :nth-child(1) > :nth-child(2) > .form-field-wrapper > .cstm-input').select('New');
    cy.wait(2000)
    cy.get(':nth-child(3) > .form-field-wrapper > .cstm-input').select('Self Generated');
    cy.wait(2000)
    cy.get('.side-modal-footer > .ms-btn-primary').click() 
    cy.wait(2000)
    cy.get('.input-error').should('contain', "Please fill this field")
    console.log('Test scenario passed')
})
//  Test case for adding a deal without First name
it('Add deal without First name', () => {
    cy.url({ timeout: 15000 }).should('include', '/dashboard')   
    cy.wait(2000)
    cy.get('.ri-function-line').click()
    cy.wait(2000)
    cy.get(':nth-child(1) > .align-items-start > .d-flex > :nth-child(3) > .py-1').click()
    cy.wait(2000)
    cy.get(':nth-child(1) > .form-field-wrapper > .cstm-input').select('lead');
    cy.wait(2000)
    cy.get('.side-modal-body > :nth-child(1) > :nth-child(2) > .form-field-wrapper > .cstm-input').select('New');
    cy.wait(2000)
    cy.get(':nth-child(3) > .form-field-wrapper > .cstm-input').select('Self Generated');
    cy.wait(2000)
    cy.get("input[placeholder='Enter first name']").focus();
    cy.wait(2000)
    const lastName = (faker.person.lastName())
    cy.get("input[placeholder='Enter last name']").type(lastName)
    cy.wait(2000)
    const phoneNumber = (faker.phone.number())
    cy.get("input[placeholder='Enter phone number']").type(phoneNumber)
    cy.wait(2000)
    const emailAddress = (faker.internet.email())
    cy.get("input[placeholder='Enter email']").type(emailAddress)
    cy.wait(2000)
    cy.get('.side-modal-footer > .ms-btn-primary').click()
    cy.wait(2000)
    cy.get('.input-error').should('contain', "Please fill this field")
    console.log('Test scenario passed')
})
//  Test case for adding a deal without Deal type
it('Add deal without Deal type', () => {
    cy.url({ timeout: 15000 }).should('include', '/dashboard')
    cy.wait(2000)
    cy.get('.ri-function-line').click()
    cy.wait(2000)
    cy.get(':nth-child(1) > .align-items-start > .d-flex > :nth-child(3) > .py-1').click()
    cy.wait(2000)
    cy.get(':nth-child(1) > .form-field-wrapper > .cstm-input').focus();
    cy.wait(2000)
    cy.get('.side-modal-body > :nth-child(1) > :nth-child(2) > .form-field-wrapper > .cstm-input').select('Self Generated');
    cy.wait(2000)
    const firstName = (faker.person.firstName())
     cy.get("input[placeholder='Enter first name']").type(firstName)
     cy.wait(2000)
    const lastName = (faker.person.lastName())
    cy.get("input[placeholder='Enter last name']").type(lastName)
    cy.wait(2000)
    const phoneNumber = (faker.phone.number())
    cy.get("input[placeholder='Enter phone number']").type(phoneNumber)
    cy.wait(2000)
    const emailAddress = (faker.internet.email())
    cy.get("input[placeholder='Enter email']").type(emailAddress)
    cy.wait(2000)
    cy.get('.side-modal-footer > .ms-btn-primary').click()
    cy.wait(2000)
    cy.get('.input-error').should('contain', "Please fill this field")
    console.log('Test scenario passed')
})
//  Test case for adding a deal without Source
it('Add deal without Source', () => {
    cy.url({ timeout: 15000 }).should('include', '/dashboard')
    cy.wait(2000)
    cy.get('.ri-function-line').click()
    cy.wait(2000)
    cy.get(':nth-child(1) > .align-items-start > .d-flex > :nth-child(3) > .py-1').click()
    cy.wait(2000)
    cy.get(':nth-child(1) > .form-field-wrapper > .cstm-input').select('lead');
    cy.wait(2000)
    cy.get('.side-modal-body > :nth-child(1) > :nth-child(2) > .form-field-wrapper > .cstm-input').select('New');
    cy.wait(2000)
    const firstName = (faker.person.firstName())
    cy.get("input[placeholder='Enter first name']").type(firstName)
    cy.wait(2000)
    const lastName = (faker.person.lastName())
    cy.get("input[placeholder='Enter last name']").type(lastName)
    cy.wait(2000)
    const phoneNumber = (faker.phone.number())
    cy.get("input[placeholder='Enter phone number']").type(phoneNumber)
    cy.wait(2000)
    const emailAddress = (faker.internet.email())
    cy.get("input[placeholder='Enter email']").type(emailAddress)
    cy.wait(2000)
    cy.get('.side-modal-footer > .ms-btn-primary').click() 
    cy.wait(2000)
    cy.get('.input-error').should('contain', "Please fill this field")
    console.log('Test scenario passed')
})
//  Test case for adding a deal without Stage
it('Add deal without Stage', () => {
    cy.url({ timeout: 15000 }).should('include', '/dashboard')
    cy.wait(2000)
    cy.get('.ri-function-line').click()
    cy.wait(2000)
    cy.get(':nth-child(1) > .align-items-start > .d-flex > :nth-child(3) > .py-1').click()
    cy.wait(2000)
    cy.get(':nth-child(1) > .form-field-wrapper > .cstm-input').select('lead');
    cy.wait(2000)
    cy.get(':nth-child(3) > .form-field-wrapper > .cstm-input').select('Self Generated');
    cy.wait(2000)
    const firstName = (faker.person.firstName())
    cy.get("input[placeholder='Enter first name']").type(firstName)
    cy.wait(2000)
    const lastName = (faker.person.lastName())
    cy.get("input[placeholder='Enter last name']").type(lastName)
    cy.wait(2000)
    const phoneNumber = (faker.phone.number())
    cy.get("input[placeholder='Enter phone number']").type(phoneNumber)
    cy.wait(2000)
    const emailAddress = (faker.internet.email())
    cy.get("input[placeholder='Enter email']").type(emailAddress)
    cy.wait(2000)
    cy.get('.side-modal-footer > .ms-btn-primary').click() 
    cy.wait(2000)
    cy.get('.input-error').should('contain', "Please fill this field")
    console.log('Test scenario passed')
})
})