/// <reference types="cypress" />

describe('Login and Navigation Tests', () => {
    
    // Test case for Login with Non-Registered Email
    it('Login with Non-Registered Email', () => {
        cy.visit("http://moserbus.local/")
        cy.wait(2000)
        cy.get('.px-3 > .nav-right-wrap > [href="/login"]').click()
        cy.wait(2000)
        // cy.get("//input[@name='email']").click()
        // cy.wait(2000)
        cy.get("input[name='email']").type('himanshupant.qa2@gmail.com')
        cy.wait(2000)
        cy.get('.ms-btn-primary').click()
        cy.wait(2000)
        cy.get('.font-16').should('contain', "Email not found!")
        cy.wait(2000)
    })
    // Test case for Login with invalid Email
    it('Login with invalid Email', () => {
        cy.visit("http://moserbus.local/")
        cy.wait(2000)
        cy.get('.px-3 > .nav-right-wrap > [href="/login"]').click()
        cy.wait(2000)
        // cy.get("//input[@name='email']").click()
        // cy.wait(2000)
        cy.get("input[name='email']").type('abc.com')
        cy.wait(2000)
        cy.get('.ms-btn-primary').click()
        cy.wait(2000)   
        cy.get('.input-error').should('contain', "Please enter a valid email address.")
        cy.wait(2000)
    })
  // Test case for Login with invalid password
    it('Login with invalid password', () => {
        cy.visit("http://moserbus.local/")
        cy.get("a[class='ms-btn-lg ms-btn-primary']").click()
        console.log('Opened Sign Up page')
        cy.wait(2000)
        cy.get(".text-link.para-16").click()
        console.log('Opened Login page')
        cy.wait(2000)
        cy.get("input[name='email']").type('himanshupant.qa@gmail.com')
        cy.wait(2000)
        cy.get("button[type='submit']").click()
        cy.wait(2000)
        cy.get("input[placeholder='Enter Your Password']").type('Harry@1235')
        cy.wait(2000)
        cy.get("button[type='submit']").click()
        cy.wait(2000)
        cy.get('.input-error').should('contain', 'Password Not Matched!')
        cy.wait(2000)
        console.log("Test passed")
    })
  
    // Test case for Login without password
    it('Login without password', () => {
        cy.visit("http://moserbus.local/")
        cy.get("a[class='ms-btn-lg ms-btn-primary']").click()
        console.log('Opened Sign Up page')
        cy.wait(2000)
        cy.get(".text-link.para-16").click()
        console.log('Opened Login page')
        cy.wait(2000)
        cy.get("input[name='email']").type('himanshupant.qa@gmail.com')
        cy.wait(2000)
        cy.get("button[type='submit']").click()
        cy.wait(2000)
        cy.get("button[type='submit']").click()
        cy.wait(2000)
        cy.get('.input-error').should('contain', 'Please fill this field')
        cy.wait(2000)
        console.log("Test passed")
    })
  // Test case for Login without email address
    it('Login without email address', () => {
        cy.visit("http://moserbus.local/")
        cy.get("a[class='ms-btn-lg ms-btn-primary']").click()
        console.log('Opened Sign Up page')
        cy.wait(2000)
        cy.get(".text-link.para-16").click()
        console.log('Opened Login page')
        cy.wait(2000)
        cy.get("input[name='email']").type('himanshupant.qa@gmail.com')
        cy.wait(2000)
        cy.get("button[type='submit']").click()
        cy.wait(2000)
        cy.get("input[name='email']").clear()
        cy.wait(2000)
        cy.get("input[placeholder='Enter Your Password']").type('Harry@123')
        cy.wait(2000)
        cy.get("button[type='submit']").click()
        cy.wait(2000)
        cy.get('.input-error').should('contain', 'Please fill this field')
        cy.wait(2000)
        console.log("Test passed")
    })

    // Test case for Login with valid creds
    it('Login with valid creds', () => {
        cy.visit("http://moserbus.local/")
        cy.get("a[class='ms-btn-lg ms-btn-primary']").click()
        console.log('Opened Sign Up page')
        cy.wait(2000)
        cy.get(".text-link.para-16").click()
        console.log('Opened Login page')
        cy.wait(2000)
        cy.get("input[name='email']").type('himanshupant.qa@gmail.com')
        cy.wait(2000)
        cy.get("button[type='submit']").click()
        cy.wait(2000)
        cy.get("input[placeholder='Enter Your Password']").type('Harry@123')
        cy.wait(2000)
        cy.get("button[type='submit']").click()
        cy.wait(2000)
        cy.url().should('include', '/dashboard')
        cy.wait(2000)
        console.log("Test passed")
    })
})
  