 / <reference types="Cypress" />
describe('Invalid login', function () {
    it('Invalid login', function (){
        cy.visit("http://moserbus.local/")
        cy.get("a[class='ms-btn-lg ms-btn-primary']").click()
        console.log('Opened Sign Up page')
        cy.wait(2000)
        cy.get(".text-link.para-16").click()
        console.log('Opened Login page')
        cy.wait(2000)
        cy.get("input[name='email']").type('himanshupant.qa2@gmail.com')
        cy.wait(2000)
        cy.get("button[type='submit']").click()
        cy.wait(2000)
        cy.get('.font-16.text-grey.text-center').should('be.visible')
        cy.wait(2000)
    })
    it('Valid login', function () {

        cy.visit("http://moserbus.local/")
        cy.get("a[class='ms-btn-lg ms-btn-primary']").click()
        console.log('Opened Sign Up page')
        cy.wait(2000)
        cy.get(".text-link.para-16").click()
        console.log('Opened Login page')
        cy.wait(2000)
        cy.get("input[name='email']").type('himanshupant.qa@gmail.com')
        cy.wait(2000)
        cy.get("button[type='submit']").click()
        cy.wait(2000)
        cy.get("input[placeholder='Enter Your Password']").type('Harry@123')
        console.log('Logged in Successfully')
        cy.wait(2000)
        cy.get("#main-app > div > div > div > div.bg-simple-pattern.d-flex.h-100.justify-content-between.flex-column > div > div > div > form > div.text-end.mt-4.w-100 > button").click()
        cy.url().should('include', '/dashboard')
        
    })
})